version: '3'

networks:
  monitor-net:
    driver: bridge

services:
  reachability:
    image: ghcr.io/ministryofjustice/staff-infrastructure-monitoring-app-reachability:main
    container_name: app-reachability
    environment:
      - PROM_USER= # basic auth username for prometheus
      - PROM_PASS= # basic auth password for prometheus
      - PROM_TARGET= # full url of http endpoint for monitoring
      - REMOTE_WRITE_URL= # url for prometheus/thanos remote write
    